//go:build ignore

// gen_icons.go fetches nvim-web-devicons Lua files and generates a Go icon
// map at icons/data.go. Run with: go run scripts/gen_icons.go
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
)

const (
	baseURL = "https://raw.githubusercontent.com/nvim-tree/nvim-web-devicons/master/lua/nvim-web-devicons/default"
	outPath = "icons/data.go"
)

// Map from Lua filename to the Go var name it populates.
var sources = map[string]string{
	"icons_by_file_extension.lua": "ByExt",
	"icons_by_filename.lua":       "ByName",
	"icons_by_operating_system.lua": "ByOS",
	"icons_by_desktop_environment.lua": "ByDE",
	"icons_by_window_manager.lua": "ByWM",
}

// Match:  ["key"] = { icon = "X", color = "#RRGGBB", cterm_color = "N", name = "..." },
var entryRE = regexp.MustCompile(`\["([^"]+)"\]\s*=\s*\{\s*icon\s*=\s*"([^"]*)",\s*color\s*=\s*"(#[0-9A-Fa-f]{6})"`)

type entry struct {
	Key   string
	Icon  string
	Color string
}

func main() {
	var b strings.Builder
	fmt.Fprintln(&b, "// Code generated by scripts/gen_icons.go; DO NOT EDIT.")
	fmt.Fprintln(&b, "// Source: https://github.com/nvim-tree/nvim-web-devicons")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package icons")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Style pairs a Nerd Font glyph with a hex color.")
	fmt.Fprintln(&b, "type Style struct {")
	fmt.Fprintln(&b, "\tIcon  string")
	fmt.Fprintln(&b, "\tColor string")
	fmt.Fprintln(&b, "}")

	// Generate maps in a stable order
	filenames := make([]string, 0, len(sources))
	for f := range sources {
		filenames = append(filenames, f)
	}
	sort.Strings(filenames)

	for _, f := range filenames {
		varName := sources[f]
		entries, err := fetchAndParse(baseURL + "/" + f)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error fetching %s: %v\n", f, err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "parsed %d entries from %s\n", len(entries), f)

		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "// %s is derived from %s.\n", varName, f)
		fmt.Fprintf(&b, "var %s = map[string]Style{\n", varName)
		for _, e := range entries {
			fmt.Fprintf(&b, "\t%q: {Icon: %q, Color: %q},\n", e.Key, e.Icon, e.Color)
		}
		fmt.Fprintln(&b, "}")
	}

	if err := os.MkdirAll("icons", 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", outPath)
}

func fetchAndParse(url string) ([]entry, error) {
	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	matches := entryRE.FindAllStringSubmatch(string(body), -1)
	entries := make([]entry, 0, len(matches))
	seen := make(map[string]bool)
	for _, m := range matches {
		key := m[1]
		if seen[key] {
			continue
		}
		seen[key] = true
		entries = append(entries, entry{Key: key, Icon: m[2], Color: m[3]})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Key < entries[j].Key })
	return entries, nil
}
